spring:
  application:
    name: clubhouseCRM
  contextPath: /
  mvc:
    view:
      suffix: .jsp
  session:
    store-type: jdbc
  jpa.properties.hibernate.connection.charSet: UTF-8
  jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
